# Generated by Django 3.2.2 on 2021-10-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_id', models.IntegerField(max_length=6)),
                ('camera', models.CharField(max_length=16)),
                ('time', models.CharField(max_length=16)),
                ('date', models.CharField(max_length=16)),
            ],
        ),
    ]
