# Generated by Django 3.2.2 on 2021-10-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NanoWareControl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='camera',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='logs',
            name='date',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='logs',
            name='photo_id',
            field=models.IntegerField(blank=True, serialize=1),
        ),
        migrations.AlterField(
            model_name='logs',
            name='time',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
