# Generated by Django 3.2.2 on 2021-10-11 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NanoWareControl', '0002_auto_20211011_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='image_link',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
