# Generated by Django 3.2.2 on 2021-10-11 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NanoWareControl', '0003_logs_image_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logs',
            name='photo_id',
        ),
    ]
