# Generated by Django 3.2.2 on 2021-10-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NanoWareControl', '0004_remove_logs_photo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='photo_id',
            field=models.IntegerField(blank=True, default=1, serialize=1),
            preserve_default=False,
        ),
    ]
