# Generated by Django 3.2.2 on 2021-10-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NanoWareControl', '0005_logs_photo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='camera',
            field=models.CharField(blank=True, default='Main', max_length=16),
        ),
    ]
