# Generated by Django 3.2.2 on 2021-10-11 16:09

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('NanoWareControl', '0006_alter_logs_camera'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='logs',
            managers=[
                ('LogsListObject', django.db.models.manager.Manager()),
            ],
        ),
    ]
