# Generated by Django 3.2.2 on 2021-10-11 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NanoWareControl', '0007_alter_logs_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='logs',
            managers=[
            ],
        ),
    ]
