# Generated by Django 3.2.2 on 2021-10-11 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NanoWareControl', '0008_alter_logs_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logs',
            name='photo_id',
        ),
    ]
