# Generated by Django 3.2.2 on 2021-10-11 16:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NanoWareControl', '0009_remove_logs_photo_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moisture_Checker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moisture_level', models.IntegerField(blank=True)),
                ('date', models.CharField(default=datetime.datetime(2021, 10, 12, 0, 32, 32, 531647), max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Water_Irrigated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_irrigated', models.IntegerField(blank=True)),
                ('date', models.CharField(default=datetime.datetime(2021, 10, 12, 0, 32, 32, 531647), max_length=16)),
            ],
        ),
    ]
