# Generated by Django 3.2.2 on 2021-10-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NanoWareControl', '0011_auto_20211012_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moisture_checker',
            name='moisture_level',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='water_irrigated',
            name='water_irrigated',
            field=models.FloatField(blank=True),
        ),
    ]
