# Generated by Django 3.2.2 on 2021-10-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NanoWareControl', '0013_toggle_manual_control'),
    ]

    operations = [
        migrations.AddField(
            model_name='toggle_manual_control',
            name='toggle_manual_controls',
            field=models.BooleanField(default=False),
        ),
    ]
