# Generated by Django 3.2.2 on 2021-10-11 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NanoWareControl', '0014_toggle_manual_control_toggle_manual_controls'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Toggle_Manual_Control',
        ),
    ]
