# Generated by Django 3.2.2 on 2021-10-13 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NanoWareControl', '0015_delete_toggle_manual_control'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seed_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed_type', models.FloatField(max_length=16)),
                ('colour_on_graph', models.CharField(max_length=16)),
                ('seed_count', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='moisture_checker',
            name='date',
            field=models.CharField(default='13 Oct', max_length=16),
        ),
        migrations.AlterField(
            model_name='water_irrigated',
            name='date',
            field=models.CharField(default='13 Oct', max_length=16),
        ),
    ]
