# Generated by Django 3.2.2 on 2021-10-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NanoWareControl', '0016_auto_20211013_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seed_type',
            name='seed_type',
            field=models.CharField(max_length=16),
        ),
    ]
