# Generated by Django 3.2.2 on 2021-10-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NanoWareControl', '0017_alter_seed_type_seed_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seed_type',
            name='colour_on_graph',
            field=models.CharField(choices=[('Red', 'Red'), ('Orange', 'Orange'), ('Yellow', 'Yellow'), ('Green', 'Green'), ('Cyan', 'Cyan'), ('Blue', 'Blue'), ('Violet', 'Violet'), ('Magenta', 'Magenta'), ('Rose', 'Rose'), ('Black', 'Black')], max_length=16),
        ),
    ]
