# Generated by Django 3.2.2 on 2021-10-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NanoWareControl', '0018_alter_seed_type_colour_on_graph'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant_Height',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_height', models.FloatField(blank=True)),
                ('date', models.CharField(default='13 Oct', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Plants_Harvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plants_harvested_count', models.FloatField(blank=True)),
                ('date', models.CharField(default='13 Oct', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Seeds_Sown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed_sown_count', models.FloatField(blank=True)),
                ('date', models.CharField(default='13 Oct', max_length=16)),
            ],
        ),
        migrations.RenameField(
            model_name='seed_type',
            old_name='seed_count',
            new_name='seed_type_count',
        ),
    ]
