# Generated by Django 3.2.2 on 2021-10-18 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NanoWareControl', '0019_auto_20211013_2350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Greengram_Plant_Height1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_height', models.FloatField(blank=True)),
                ('date', models.CharField(default='19 Oct', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Greengram_Plant_Height2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_height', models.FloatField(blank=True)),
                ('date', models.CharField(default='19 Oct', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Greengram_Plant_Height3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_height', models.FloatField(blank=True)),
                ('date', models.CharField(default='19 Oct', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Tomato_Plant_Height1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_height', models.FloatField(blank=True)),
                ('date', models.CharField(default='19 Oct', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Tomato_Plant_Height2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_height', models.FloatField(blank=True)),
                ('date', models.CharField(default='19 Oct', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Tomato_Plant_Height3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_height', models.FloatField(blank=True)),
                ('date', models.CharField(default='19 Oct', max_length=16)),
            ],
        ),
        migrations.DeleteModel(
            name='Plant_Height',
        ),
        migrations.AlterField(
            model_name='moisture_checker',
            name='date',
            field=models.CharField(default='19 Oct', max_length=16),
        ),
        migrations.AlterField(
            model_name='plants_harvest',
            name='date',
            field=models.CharField(default='19 Oct', max_length=16),
        ),
        migrations.AlterField(
            model_name='seeds_sown',
            name='date',
            field=models.CharField(default='19 Oct', max_length=16),
        ),
        migrations.AlterField(
            model_name='water_irrigated',
            name='date',
            field=models.CharField(default='19 Oct', max_length=16),
        ),
    ]
