# Generated by Django 3.2.2 on 2021-10-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NanoWareControl', '0020_auto_20211019_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greengram_plant_height1',
            name='date',
            field=models.CharField(default='20 Oct', max_length=16),
        ),
        migrations.AlterField(
            model_name='greengram_plant_height2',
            name='date',
            field=models.CharField(default='20 Oct', max_length=16),
        ),
        migrations.AlterField(
            model_name='greengram_plant_height3',
            name='date',
            field=models.CharField(default='20 Oct', max_length=16),
        ),
        migrations.AlterField(
            model_name='moisture_checker',
            name='date',
            field=models.CharField(default='20 Oct', max_length=50),
        ),
        migrations.AlterField(
            model_name='plants_harvest',
            name='date',
            field=models.CharField(default='20 Oct', max_length=16),
        ),
        migrations.AlterField(
            model_name='seeds_sown',
            name='date',
            field=models.CharField(default='20 Oct', max_length=16),
        ),
        migrations.AlterField(
            model_name='tomato_plant_height1',
            name='date',
            field=models.CharField(default='20 Oct', max_length=16),
        ),
        migrations.AlterField(
            model_name='tomato_plant_height2',
            name='date',
            field=models.CharField(default='20 Oct', max_length=16),
        ),
        migrations.AlterField(
            model_name='tomato_plant_height3',
            name='date',
            field=models.CharField(default='20 Oct', max_length=16),
        ),
        migrations.AlterField(
            model_name='water_irrigated',
            name='date',
            field=models.CharField(default='20 Oct', max_length=16),
        ),
    ]
